verbose = false

[project]
name = "test-project"
version = "0.1.0"
description = "A Nagari project"
main = "main.nag"
source_dir = "src"
output_dir = "dist"

[build]
target = "js"
optimization = false
sourcemap = true
minify = false
jsx = false
declarations = false
treeshake = false
external = []

[build.define]

[lsp]
enabled = true
diagnostics = true
completion = true
hover = true
goto_definition = true
find_references = true
rename = true
code_actions = true

[format]
indent_size = 4
max_line_length = 100
use_tabs = false
trailing_commas = true
quote_style = "double"
space_around_operators = true

[lint]
enabled_rules = []
disabled_rules = []
ignore_patterns = []
max_line_length = 100
max_complexity = 10
allow_unused_variables = false
allow_unused_imports = false
strict_typing = true

[lint.rule_severity]

[test]
test_pattern = "**/*.test.nag"
timeout = 30
parallel = true
coverage = false

[package]
registry = "https://registry.nagari.dev"
cache_dir = ".nagari/cache"
lockfile = "nagari-lock.toml"
auto_install = true
